import {useEffect,useState} from 'react'
import {ArrowDown,ArrowUpRight,BookOpen,Download,Github,GraduationCap,Linkedin,Menu,X} from 'lucide-react'

const links={github:'https://github.com/GKARAMOU',linkedin:'https://www.linkedin.com/in/giorgos-karamousalis-880731301'}
const projects=[
 {tag:'Flagship full-stack product',title:'SupplyPilot — Operations Command Center',copy:'Inventory, purchasing and expense platform inspired by real retail workflows, with a JWT-secured Spring Boot API, PostgreSQL, Redis, RabbitMQ, observability and CI/CD.',stack:['Java 21','Spring Boot','React','PostgreSQL'],href:'https://github.com/GKARAMOU/supplypilot',demo:'https://gkaramou.github.io/supplypilot/',preview:'supplypilot'},
 {tag:'AI product',title:'CareerFlow — Job Search Command Center',copy:'A full-stack application tracker with an interactive dashboard, JWT-secured FastAPI backend, PostgreSQL persistence, resume-fit analysis and CI/CD.',stack:['React','TypeScript','FastAPI','PostgreSQL'],href:'https://github.com/GKARAMOU/careerflow-ai',demo:'https://gkaramou.github.io/careerflow-ai/',preview:'careerflow'},
 {tag:'Full-stack',title:'Restaurant Reservation App',copy:'Reservation platform with account creation, JWT login, restaurant discovery and complete booking management.',stack:['React','Node.js','Express','MariaDB'],href:'https://github.com/GKARAMOU/restaurant-reservation-app',preview:'restaurant'},
 {tag:'Backend',title:'Spring Secure API',copy:'Production-ready REST API with role-based access, MySQL persistence, OpenAPI documentation and containerized delivery.',stack:['Java','Spring Boot','JWT','MySQL'],href:'https://github.com/GKARAMOU/spring-secure-task-api',preview:'spring'},
 {tag:'Backend',title:'FastAPI Notes Service',copy:'Async Python API with PostgreSQL, secure authentication, user-scoped resources, tests and Docker Compose.',stack:['Python','FastAPI','PostgreSQL','Pytest'],href:'https://github.com/GKARAMOU/fastapi-secure-notes-api',preview:'fastapi'},
 {tag:'DevOps',title:'Web Quality Pipeline',copy:'Automated browser checks with CI quality gates, reports, artifacts and a reproducible Docker workflow.',stack:['Selenium','Pytest','GitHub Actions','Docker'],href:'https://github.com/GKARAMOU/web-quality-pipeline',preview:'pipeline'}
]
const skills=[['Languages','Java, Python, JavaScript, SQL'],['Backend','Spring Boot, FastAPI, Node.js, REST APIs'],['Frontend','React, HTML, CSS, responsive UI'],['Data & AI','PyTorch, Transformers, scikit-learn, pandas'],['Databases','PostgreSQL, MySQL, MariaDB'],['Delivery','Git, Docker, GitHub Actions, testing']]
function ProjectPreview({type}){
 if(type==='supplypilot')return <div className="appPreview supplyPreview"><img src="/projects/supplypilot-dashboard.png" alt="SupplyPilot inventory and purchasing dashboard"/></div>
 if(type==='careerflow')return <div className="appPreview careerPreview"><img src="/projects/careerflow-dashboard.png" alt="CareerFlow job application dashboard"/></div>
 if(type==='restaurant')return <div className="appPreview restaurantPreview"><div className="previewBar"><i/><i/><i/><span>tablely / reservations</span></div><div className="restaurantBody"><div><small>ATHENS · TONIGHT</small><h4>Find your table.</h4><p>Curated restaurants, instant reservations.</p><button>Explore restaurants</button></div><div className="bookingCard"><b>Olive & Stone</b><span>Modern Greek · 4.8 ★</span><div><i>19:00</i><i>20:30</i><i>21:00</i></div></div></div></div>
 if(type==='spring')return <div className="appPreview apiPreview"><div className="previewBar"><i/><i/><i/><span>localhost:8080 / swagger-ui</span></div><div className="apiBody"><div className="apiTitle"><b>Secure Task API</b><span>1.0.0</span></div><p>OpenAPI 3 · authenticated task management</p><div className="endpoint"><strong>GET</strong><code>/api/tasks</code><span>List tasks</span></div><div className="endpoint post"><strong>POST</strong><code>/api/tasks</code><span>Create task</span></div><div className="response"><small>200 RESPONSE</small><code>{`{"title":"Ship API","status":"IN_PROGRESS"}`}</code></div></div></div>
 if(type==='fastapi')return <div className="appPreview notesPreview"><div className="previewBar"><i/><i/><i/><span>Notespace</span></div><div className="notesBody"><aside><b>N.</b><span>All notes</span><span>Favorites</span><span>Archive</span></aside><div><small>YOUR WORKSPACE</small><h4>Good morning, Georgios.</h4><div className="noteGrid"><article><i>BACKEND</i><b>FastAPI architecture</b><p>Async sessions, scoped queries and JWT flow.</p></article><article><i>IDEAS</i><b>Portfolio launch</b><p>Final checklist and repository links.</p></article></div></div></div></div>
 return <div className="appPreview pipelinePreview"><div className="previewBar"><i/><i/><i/><span>GitHub Actions / CI #42</span></div><div className="pipelineBody"><div className="successMark">✓</div><div><small>WORKFLOW RUN</small><h4>All checks passed</h4><p>main · 3f8a21c · 1m 34s</p></div><ul><li><span>✓</span>Install dependencies <b>12s</b></li><li><span>✓</span>Run Selenium smoke tests <b>48s</b></li><li><span>✓</span>Build Docker image <b>31s</b></li><li><span>✓</span>Upload test reports <b>3s</b></li></ul></div></div>
}
function App(){
 const [open,setOpen]=useState(false)
 useEffect(()=>{const close=()=>setOpen(false);addEventListener('hashchange',close);return()=>removeEventListener('hashchange',close)},[])
 const nav=['about','education','skills','experience','projects','research','contact']
 return <div className="site">
  <a className="skip" href="#main">Skip to content</a>
  <header><a className="brand" href="#top" aria-label="Home"><span>GK</span><i/></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{nav.map(n=><a key={n} href={'#'+n}>{n}</a>)}</nav><a className="navCta" href="/Georgios_Karamousalis_CV.pdf" download><Download size={16}/> CV</a></header>
  <main id="main">
   <section className="hero" id="top"><div className="eyebrow"><span/>Available for software engineering opportunities</div><h1>I build reliable software at the intersection of <em>backend engineering</em> and AI.</h1><p className="lede">Computer Science graduate and MSc Artificial Intelligence candidate, focused on robust APIs, applied machine learning and thoughtful digital products.</p><div className="actions"><a className="primary" href="#projects">Explore my work <ArrowDown/></a><a className="secondary" href={links.linkedin} target="_blank" rel="noreferrer">Connect on LinkedIn <ArrowUpRight/></a></div><div className="signal"><div><b>06</b><span>featured projects</span></div><div><b>80.3%</b><span>stance model accuracy</span></div><div><b>03</b><span>production stacks</span></div></div></section>
   <section id="about" className="two"><div><p className="kicker">01 / About</p><h2>Curious by nature.<br/>Practical by design.</h2></div><div className="body"><p>I enjoy turning complex requirements into clean, maintainable systems. My background combines full-stack development, database design and applied NLP research.</p><p>Alongside academic work, operational roles in military administration and a family wine business strengthened my accuracy, accountability, customer service and ability to work under pressure.</p></div></section>
   <section id="education"><p className="kicker">02 / Education</p><div className="timeline"><article><GraduationCap/><div><small>MSc · In progress</small><h3>Artificial Intelligence</h3><p>Deep learning, natural language processing, model evaluation and applied research.</p></div></article><article><BookOpen/><div><small>2022 — September 2025</small><h3>BSc Computer Science</h3><p>Metropolitan College, Athens · Software engineering, databases, distributed systems and data analysis.</p></div></article></div></section>
   <section id="skills"><p className="kicker">03 / Capabilities</p><h2>A full-stack toolkit,<br/>grounded in fundamentals.</h2><div className="skillGrid">{skills.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
   <section id="experience"><p className="kicker">04 / Experience</p><div className="roles"><article><small>Operational experience</small><h3>Expenditure & Supply Office · Hellenic Army</h3><p>Supported expense records, supply documentation and day-to-day administrative workflows where accuracy and confidentiality were essential.</p></article><article><small>Family business</small><h3>Retail Operations · Family Wine Shop</h3><p>Supported customers, inventory handling, merchandising and daily operations in a fast-moving retail environment.</p></article></div></section>
   <section id="projects"><p className="kicker">05 / Selected work</p><div className="sectionHead"><h2>Built to be used,<br/>tested and understood.</h2><a href={links.github}>All repositories <ArrowUpRight/></a></div><div className="projects">{projects.map((p,i)=><article className="projectCase" key={p.title}><ProjectPreview type={p.preview}/><div className="projectInfo"><div className="projectNo">0{i+1}</div><div><small>{p.tag}</small><h3>{p.title}</h3><p>{p.copy}</p><ul>{p.stack.map(s=><li key={s}>{s}</li>)}</ul><div className="projectLinks">{p.demo&&<a href={p.demo} target="_blank" rel="noreferrer">Live demo <ArrowUpRight size={16}/></a>}<a href={p.href} target="_blank" rel="noreferrer">Repository <Github size={16}/></a></div></div></div></article>)}</div></section>
   <section id="research" className="research"><p className="kicker">06 / Research</p><div className="researchGrid"><article><span>BSc thesis</span><h3>Social Network Analysis for Influencer Detection</h3><p>Graph-based analysis using NetworkX and Gephi to identify influential nodes and communities through centrality, PageRank and community detection.</p></article><article className="featured"><span>MSc thesis · In progress</span><h3>Stance Detection with Deep Learning</h3><p>Target-aware classification of online discussion into FAVOR, AGAINST and NEUTRAL. Compared TF-IDF baselines with BERT and RoBERTa across VAST and EZ-STANCE.</p><div className="metric"><b>0.803</b><small>Macro-F1 · best RoBERTa experiment</small></div></article></div></section>
   <section id="contact" className="contact"><p className="kicker">07 / Contact</p><h2>Have a problem worth solving?</h2><p>Based in Greece and open to remote, junior software engineering, backend and applied AI opportunities.</p><a className="contactLink" href={links.linkedin} target="_blank" rel="noreferrer">LinkedIn Profile <ArrowUpRight/></a><div className="socials"><a href={links.github}><Github/>GitHub</a><a href={links.linkedin}><Linkedin/>LinkedIn</a><a href="/Georgios_Karamousalis_CV.pdf" download><Download/>Download CV</a></div></section>
  </main><footer><span>© 2026 Georgios Karamousalis</span><span>Designed and engineered with care.</span></footer>
 </div>
}
export default App
